
#기본 설정
spring:
  profiles:
    active: h2 #실행 profile 설정
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성 자동 업데이트
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true  # (3) SQL pretty print
#  sql:
#    init:
#      data-locations: classpath:data.sql
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESSORY}
      secretKey: ${AWS_SECRECY_ACCESSORY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    s3:
      bucket: ${AWS_BUCKET}


server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 40
  refresh-token-expiration-minutes: 420

