
#기본 설정
spring:
  profiles:
    active: rds #실행 profile 설정
  jpa:
    hibernate:
      ddl-auto: update  # (1) 스키마 자동 생성 자동 업데이트
      org:
        hibernate:
          # 로그 레벨을 INFO로 설정
          level: INFO
cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_ACCESS_KEY}
    region:
      static: ${AWS_REGION}
    stack:
      auto: false
    s3:
      bucket: ${S3_BUCKET_NAME}


server:
  servlet:
    encoding:
      force-response: true
mail:
  address:
    admin: admin@gmail.com
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 180
  refresh-token-expiration-minutes: 420

